# Generated by Django 4.0.3 on 2022-03-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor_rating',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
