# Generated by Django 3.2.14 on 2022-07-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiration_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
